#!python

import subprocess
import os

Import('env openscad2 openscad_counter openscad_echo')

parts = {'top': 17,
         'bottom': 10,
         'right': 2,
         'left': 2,
         'up': 2,
         'down': 2,
         'ok': 2,
         'reset': 2}

for part in parts:
  openscad_counter(target='function_generator_' + part,
                   source=['function_generator_box'], counter=parts[part])

env.Alias('function_generator',
          ['function_generator_' + part + suffix
           for part in parts
           for suffix in ['.stl']])
