#!python
import itertools

Import('env openscad2')
printable_parts = ['top', 'button']
all_parts = ['demo'] + printable_parts

for part in all_parts:
  openscad2(target='box_button_demo_' + part,
            source=['box_button_demo'], path="src/box_button_demo")

env.Alias('box_button_demo',
          ['box_button_demo_' + part + suffix
           for part in all_parts
           for suffix in ['.png', '.stl']])

env.Alias('box_button_demo_printable_parts',
          ['box_button_demo_' + part + '.stl'
           for part in printable_parts])
