#!python
import itertools

Import('env openscad2 openscad_counter')

parts = {'top': 3,
         'bottom': 2,
         'button': 2}

for part in parts:
  openscad_counter(target='box_button_demo_' + part,
                   source=['box_button_demo'], counter=parts[part])

env.Alias('box_button_demo',
          ['box_button_demo_' + part + suffix
           for part in parts
           for suffix in ['.stl']])
