#!python
import itertools

Import('env openscad2 openscad_counter')

parts = {'top': 3,
         'bottom': 3}

for part in parts:
  openscad_counter(target='box_screw_post_demo_' + part,
                   source=['box_screw_post_demo'], counter=parts[part])

env.Alias('box_screw_post_demo',
          ['box_screw_post_demo_' + part + suffix
           for part in parts
           for suffix in ['.stl']])
