#!python
import itertools

Import('env openscad2')
printable_parts = ['holes']
all_parts = printable_parts

for part in all_parts:
  openscad2(target=part,
               source=[part])

env.Alias('holes_demo',
          list(itertools.chain([[part + '.stl', part + '.png']
                                for part in all_parts])))

env.Alias('holes_demo_printable_parts',
          [part + '.stl'
           for part in printable_parts])
