#!python

Import('env openscad2 openscad_counter')

parts = {'top': 12,
         'bottom': 9,
         'button': 2}

for part in parts:
  openscad_counter(target='esr_tester_' + part,
            source=['esr_tester_box'], counter=parts[part])

env.Alias('esr_tester',
          ['esr_tester_' + part + suffix
           for part in parts
           for suffix in ['.stl']])
