#!python
import itertools

Import('env')
printable_parts = ['button', 'top', 'bottom']
all_parts = ['demo'] + printable_parts

for part in all_parts:
  env.Openscad(target='esr_tester_' + part,
               source=['esr_tester_box'])

env.Alias('esr_tester',
          list(itertools.chain([[part + '.stl', part + '.png']
                              for part in all_parts])))

env.Alias('esr_tester_printable_parts',
          ['esr_tester_' + part + '.stl'
           for part in printable_parts])
