#!python
import itertools

Import('env openscad2')
printable_parts = ['button', 'top', 'bottom']
all_parts = ['demo'] + printable_parts

for part in all_parts:
  openscad2(target='esr_tester_' + part,
               source=['esr_tester_box'], path="src/esr_tester")

env.Alias('esr_tester',
          ['esr_tester_' + part + suffix
           for part in all_parts
           for suffix in ['.png', '.stl']])

env.Alias('esr_tester_printable_parts',
          ['esr_tester_' + part + '.stl'
           for part in printable_parts])
