#!python
import itertools

Import('env openscad2')
printable_parts = ['top', 'bottom']
all_parts = ['demo'] + printable_parts

for part in all_parts:
  openscad2(target='box_screen_demo_' + part,
            source=['box_screen_demo'], path="src/box_screen_demo")

env.Alias('box_screen_demo',
          ['box_screen_demo_' + part + suffix
           for part in all_parts
           for suffix in ['.png', '.stl']])

env.Alias('box_screen_demo_printable_parts',
          ['box_screen_demo_' + part + '.stl'
           for part in printable_parts])
