#!python
import itertools

Import('env openscad2 openscad_counter')

parts = {'top': 3,
         'bottom': 2}

for part in parts:
  openscad_counter(target='box_screen_demo_' + part,
                   source=['box_screen_demo'], counter=parts[part])

env.Alias('box_screen_demo',
          ['box_screen_demo_' + part + suffix
           for part in parts
           for suffix in ['.stl']])
